fix error caused by 'MyAudioProcessorChain'
playerFailed [eventTime=33.95, mediaPos=0.00, window=0, period=0, errorCode=ERROR_CODE_AUDIO_TRACK_INIT_FAILED
  androidx.media3.exoplayer.ExoPlaybackException: MediaCodecAudioRenderer error, index=1, format=Format(0, null, null, audio/raw, null, -1, en, [-1, -1, -1.0, null], [2, 44100]), format_supported=YES
  Caused by: androidx.media3.exoplayer.audio.AudioSink$ConfigurationException
  Caused by: androidx.media3.common.audio.NonFinalChannelMixingAudioProcessor: No mixing matrix for input channel count AudioFormat[sampleRate=44100, channelCount=2, encoding=2]

Problem:
  https://github.com/androidx/media/blob/1.8.0/libraries/common/src/main/java/androidx/media3/common/audio/ChannelMixingAudioProcessor.java#L59-L64

Where:
  * MyAudioProcessorChain.DownmixBaseAudioProcessor
    - extends NonFinalChannelMixingAudioProcessor
  * MyAudioProcessorChain.DownmixSurroundToStereoAudioProcessor
    - extends MyAudioProcessorChain.DownmixBaseAudioProcessor
    - supports inputAudioFormat.channelCount = [3..6]
  * MyAudioProcessorChain.DownmixStereoToMonoAudioProcessor
    - extends MyAudioProcessorChain.DownmixBaseAudioProcessor
    - supports inputAudioFormat.channelCount = [2]

Solution:
  * override ChannelMixingAudioProcessor.onConfigure()
  * call parent implementation in try/catch
  * when caught, indicate that the output audio format is NOT_SET